### ISSUE TITLE
I can't reinstall

### ISSUE THREAD

**Issue by Crispydogs101** [infinitytec/2.0-Colors#9]
Because while checking to see if I installed it I accidentally removed it and so I tried to reinstall it with tapermonkey and it's not letting me because when I click it, it just exits out and doesn't even download anything.

**Comment by infinitytec** [comment]
Open up the extension dashboard. For me it installed.

**Comment by Crispydogs101** [comment]
> Open up the extension dashboard. For me it installed.

![Screenshot 2024-01-02 061439](https://github.com/infinitytec/2.0-Colors/assets/114325424/e1f19ba0-f665-4928-9f92-dd6599af307d)
I see it. 

Edit: ignore how I closed it that was a mistake

**Comment by Crispydogs101** [comment]
Ok but now a new issue is that the scratch looks the same. Still like it was before.

**Comment by Crispydogs101** [comment]
> Ok but now a new issue is that the scratch looks the same. Still like it was before.

How do I make it activated or something

**Comment by infinitytec** [comment]
You need to make sure that the userscript is set to enabled in the Tampermonkey dashboard. 

This script will only change block colors. I haven't updated it for a few years so I can't guarantee that it fully works, but I just tried it and it seems to work. If you want to change the entire interface to look more like Scratch 2.0 you can use this: https://github.com/infinitytec/I-Cant-Believe-Its-Not-2

Keep in mind I haven't updated that one in a while either. If you want a more up-to-date (and frankly more useful) theming engine, I recommend Scratch Addons: https://github.com/ScratchAddons/ScratchAddons

**Comment by Crispydogs101** [comment]
> You need to make sure that the userscript is set to enabled in the Tampermonkey dashboard.
> 
> This script will only change block colors. I haven't updated it for a few years so I can't guarantee that it fully works, but I just tried it and it seems to work. If you want to change the entire interface to look more like Scratch 2.0 you can use this: https://github.com/infinitytec/I-Cant-Believe-Its-Not-2
> 
> Keep in mind I haven't updated that one in a while either. If you want a more up-to-date (and frankly more useful) theming engine, I recommend Scratch Addons: https://github.com/ScratchAddons/ScratchAddons

I used the second github thingy you linked and it still looks the same. How can I activate something for it to actually work? Like in a step by step kinda way?

**Comment by infinitytec** [comment]
> > You need to make sure that the userscript is set to enabled in the Tampermonkey dashboard.
> > This script will only change block colors. I haven't updated it for a few years so I can't guarantee that it fully works, but I just tried it and it seems to work. If you want to change the entire interface to look more like Scratch 2.0 you can use this: https://github.com/infinitytec/I-Cant-Believe-Its-Not-2
> > Keep in mind I haven't updated that one in a while either. If you want a more up-to-date (and frankly more useful) theming engine, I recommend Scratch Addons: https://github.com/ScratchAddons/ScratchAddons
> 
> I used the second github thingy you linked and it still looks the same. How can I activate something for it to actually work? Like in a step by step kinda way?

It's in the Themes section of the extension's settings.

**Comment by Crispydogs101** [comment]
> > > You need to make sure that the userscript is set to enabled in the Tampermonkey dashboard.
> > > This script will only change block colors. I haven't updated it for a few years so I can't guarantee that it fully works, but I just tried it and it seems to work. If you want to change the entire interface to look more like Scratch 2.0 you can use this: https://github.com/infinitytec/I-Cant-Believe-Its-Not-2
> > > Keep in mind I haven't updated that one in a while either. If you want a more up-to-date (and frankly more useful) theming engine, I recommend Scratch Addons: https://github.com/ScratchAddons/ScratchAddons
> > 
> > 
> > I used the second github thingy you linked and it still looks the same. How can I activate something for it to actually work? Like in a step by step kinda way?
> 
> It's in the Themes section of the extension's settings.

I'm not able to find it.

**Comment by infinitytec** [comment]
> > > > You need to make sure that the userscript is set to enabled in the Tampermonkey dashboard.
> > > > This script will only change block colors. I haven't updated it for a few years so I can't guarantee that it fully works, but I just tried it and it seems to work. If you want to change the entire interface to look more like Scratch 2.0 you can use this: https://github.com/infinitytec/I-Cant-Believe-Its-Not-2
> > > > Keep in mind I haven't updated that one in a while either. If you want a more up-to-date (and frankly more useful) theming engine, I recommend Scratch Addons: https://github.com/ScratchAddons/ScratchAddons
> > > 
> > > 
> > > I used the second github thingy you linked and it still looks the same. How can I activate something for it to actually work? Like in a step by step kinda way?
> > 
> > 
> > It's in the Themes section of the extension's settings.
> 
> I'm not able to find it.

Open up the Scratch Addon extension and go to its settings.

**Comment by GrahamSH-LLK** [comment]
Install at https://scratchaddons.com/install, then go to https://scratch.mit.edu/scratch-addons-extension/settings and search for Customizable block colors and choose the Scratch 2 preset at the bottom.
